name: pet_perfect
description: Assignment App by Suraj Sisodia for Pet Perfect.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true